kind: Patterns
patterns:
  - Ng cluster:
      pattern: "ŋ<VelStop>"
      _ref: "<Ng>"
      test_includes: ["ŋk", "ŋg"]
      test_excludes: ["nk", "ng", "ŋt", "ŋd", "ŋs", "tŋ", "dŋ", "sŋ"]
  - Coronal sequence:
      pattern: "<CorObs><CorObs>+"
      _ref: "<CorSeq>"
      test_includes: [
        "tt", "td", "ts", "t̪t", "t̪d", "dt", "dd", "ds",
        "d̪t", "d̪d", "st", "sd", "ss", "s̪t", "s̪d", "t̪t",
        "t̪d", "t̪s", "t̪t̪", "t̪d̪", "d̪t", "d̪d", "d̪s", "d̪t̪",
        "d̪d̪", "ttd", "tts", "tt̪", "ttt", "ttd̪", "tdd", "tds",
        "tð", "ðð", "ððd"
      ]
      test_excludes: [
        "kk", "kg", "kŋ", "gk", "gg", "gŋ", "ŋk", "ŋg", "tŋ",
        "dŋ", "sŋ", "t̪ŋ", "d̪ŋ", "t", "d", "s", "t̪", "d̪",
      ]
  - Velar-coronal cluster:
    # doesn't actually happen in Tira (afaik) but useful for demoing Pattern composition
      pattern: "<VelStop><CorObs>"
      _ref: "<VelCor>"
      test_includes: ["kt", "kd", "ks", "kt̪", "kd̪", "gt", "gd", "gs", "gt̪", "gd̪"]
      test_excludes: [
        "kk", "kg", "kŋ", "gk", "gg", "gŋ", "ŋk", "ŋg", "tŋ", "dŋ",
        "sŋ", "t̪ŋ", "d̪ŋ", "t", "d", "s", "t̪", "d̪", "k", "g",
      ]