kind: Patterns
patterns:
  - Syllable_nucleus:
      _ref: "<Syllable_Nucleus>"
      pattern: "{<V><N>rl}?<T>"
      test_includes: ["ᴐ́", "à", "r̀", "ŋ̂", "ǹ", "ǎ"]
      test_excludes: ["a", "p", "rl", "nd", "àpɾí", "m"]
  - Syllable coda:
      _ref: "<Syllable_Rhyme>"
      pattern: "<Syllable_Nucleus><C>*{<C>}"
      test_includes: ["àp", "r̀l", "ŋ̂", "ǹd̪", "ǎ"]
      test_excludes: ["pᴐ́", "ràp", "kr̀l", "tŋ̂", "lɜ̀ǹd̪", "lǎ"]
  - Syllable:
      _ref: "<Syllable>"
      pattern: "<C>*<Syllable_Rhyme>*"
      test_includes: ["pᴐ́", "àp", "r̀l", "ŋ̂", "ǹd̪", "pǎp"]
      test_excludes: ["p", "a", "ap", "rl", "nd", "àpɾí"]
