kind: Patterns
patterns:
- ref: Syllable
  ref: <Syll>
  pattern: <C>?<V><T><C>?<C>?
  test_includes:
  - páŋk
  - chə̀rt
  - á
  - ɪ̀g
  test_excludes:
  - páŋkk
  - schə̀rt
  - a
  - chərt
  - ɪg
- ref: Monosyllable word
  ref: <MonoSyllWord>
  pattern: '#<Syll>#'
  test_includes:
  - páŋk
  - chə̀rt
  - á
  - ɪ̀g
  test_excludes:
  - páŋkpáŋk
  - chə̀rtpáŋk
  - ìá
  - ɪ̀gə́
- ref: Disyllable word
  ref: <DiSyllWord>
  pattern: '#<Syll><Syll>#'
  test_includes:
  - páŋkpáŋk
  - chə̀rtpáŋk
  - ìá
  - ɪ̀gə́
  test_excludes:
  - páŋk
  - chə̀rt
  - á
  - ɪ̀g
  - páŋkpáŋkì
  - ɪ̀gə́rà
