kind: Inventory
data:
- ref: <Slot>
  name: Morphological slot
  tags:
  - '[CL]'
- ref: <FV>
  name: Final vowel class
  tags:
  - '[aɔ]'
  - '[ao]'
  - '[ai]'
  - '[ɔɔ]'
  - '[ɔu]'
  - '[ɔi]'
- ref: <ACC>
  name: Accusative tag
  tags:
  - '[-a]'
  - '[-ɛ]'
  - '[-ɔ]'
  - '[-ŋù]'
  - '[-ɲa]'
- ref: <noun_number>
  name: number flags
  tags:
  - '[sg]'
  - '[pl]'
