kind: Inventory
data:
  - ref: consonants
    ref: <C>
    _children:
    - ref: stops
      ref: <Plsv>
      _children:
        - ref: voiced
          ref: <B>
          phones:
          - b
          - d̪
          - d
          - ɟ
          - g
        - ref: voiceless
          ref: <P>
          phones:
          - p
          - t̪
          - t
          - c
          - k
          - ʔ
    - ref: nasals
      ref: <N>
      phones:
      - m
      - n
      - ɲ
      - ŋ
    - ref: fricatives
      ref: <F>
      phones:
      - f
      - v
      - ð
      - s
      - ʃ
      - h
    - ref: resonants
      ref: <R>
      phones:
      - r
      - ɾ
      - ɽ
      - l
      - w
      - j
  - ref: vowels
    ref: <V>
    _children:
    - ref: high
      ref: <V_High>
      phones:
      - i
      - ɪ
      - u
      - ʊ
    - ref: mid
      ref: <V_Mid>
      phones:
      - e
      - ɛ
      - ə
      - ɜ
      - o
      - ɔ
    - ref: low
      ref: <V_Low>
      phones:
      - a
