kind: Inventory
data:
- ref: <TONE_SLOT>
  name: Tone flags
  tags:
  - '[TBU]'
  - '[FLOAT]'
- ref: <T>
  name: Tones
  _children:
  - ref: <HL>
    name: Falling
    phones:
    - ̂
  - ref: <H>
    name: High
    phones:
    - ́
  - ref: <L>
    name: Low
    phones:
    - ̀
  - ref: <LH>
    name: Rising
    phones:
    - ̌
