kind: Inventory
data:
  Tone flags:
    _ref: <TONE_SLOT>
    _flags:
    - '[TBU]'
    - '[FLOAT]'
  Tones:
    _ref: <T>
    Falling:
      _ref: <HL>
      _phones:
      - ̂
    High:
      _ref: <H>
      _phones:
      - ́
    Low:
      _ref: <L>
      _phones:
      - ̀
    Rising:
      _ref: <LH>
      _phones:
      - ̌
