# Imperfect indicative suffixes for -ar verbs
# hablar: hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban
kind: FeatureMarkers
feature: person_number
global_order: suffixation
markers:
  1sg:
    type: suffix
    value: "-aba"
  2sg:
    type: suffix
    value: "-abas"
  3sg:
    type: suffix
    value: "-aba"
  1pl:
    type: suffix
    value: "-ábamos"
  2pl:
    type: suffix
    value: "-abais"
  3pl:
    type: suffix
    value: "-aban"
