# Present indicative suffixes for -er verbs
# comer: como, comes, come, comemos, coméis, comen
kind: FeatureMarkers
feature: person_number
global_attributes:
  order: suffixation
markers:
  1sg:
    suffix: "-o"
  2sg:
    suffix: "-es"
  3sg:
    suffix: "-e"
  1pl:
    suffix: "-emos"
  2pl:
    suffix: "-éis"
  3pl:
    suffix: "-en"
