# Present indicative suffixes for -ar verbs
# hablar: hablo, hablas, habla, hablamos, habláis, hablan
kind: FeatureMarkers
feature: person_number
global_order: suffixation
markers:
  1sg:
    type: suffix
    value: "-o"
  2sg:
    type: suffix
    value: "-as"
  3sg:
    type: suffix
    value: "-a"
  1pl:
    type: suffix
    value: "-amos"
  2pl:
    type: suffix
    value: "-áis"
  3pl:
    type: suffix
    value: "-an"
