# Present indicative suffixes for -ar verbs
# hablar: hablo, hablas, habla, hablamos, habláis, hablan
kind: FeatureMarkers
feature: person_number
global_attributes:
  order: suffixation
markers:
  1sg:
    suffix: "-o"
  2sg:
    suffix: "-as"
  3sg:
    suffix: "-a"
  1pl:
    suffix: "-amos"
  2pl:
    suffix: "-áis"
  3pl:
    suffix: "-an"
