kind: ContingentFeatureMarkers
global_order: argument_marking
features: ["tam", "subject"]
markers:
- features: {tam: perfective, subject: 1sg}
  realization:
  - {kind: suffix, value: -íŋí}
- features: {tam: perfective, subject: 2sg}
  realization:
  - {kind: suffix, value: -áŋá}
- features: {tam: perfective, subject: 1dual.incl}
  realization:
  - {kind: suffix, value: -ɜ́llí}
- features: {tam: perfective, subject: 1pl.incl}
  realization:
  - {kind: suffix, value: -ɜ́llí-r}
- features: {tam: perfective, subject: 1pl.excl}
  realization:
  - {kind: suffix, value: -áɲà}
- features: {tam: perfective, subject: 2pl}
  realization:
  - {kind: suffix, value: -áɲá}
