kind: ContingentFeatureMarkers
features: ["tam", "deixis"]
markers:
- features: {tam: imperfective, deixis: itive}
  realization:
  - {type: rule, value: set_hl_melody, order: tone_melody}
  - {type: rule, value: ipfv_it_fv, order: fv_assignment}
  - {type: prefix, value: '[CL]-á_', order: argument_marking}
- features: {tam: imperfective, deixis: ventive}
  realization:
  - {type: rule, value: set_all_low_tone, order: tone_melody}
  - {type: rule, value: ipfv_pfv_vent_fv, order: fv_assignment}
  - {type: prefix, value: '[CL]-á_', order: argument_marking}
- features: {tam: perfective, deixis: itive}
  realization:
  - {type: rule, value: set_hl_melody, order: tone_melody}
  - {type: rule, value: pfv_it_fv, order: fv_assignment}
  - {type: prefix, value: '[CL]-à_', order: argument_marking}
- features: {tam: perfective, deixis: ventive}
  realization:
  - {type: rule, value: set_all_low_tone, order: tone_melody}
  - {type: rule, value: ipfv_pfv_vent_fv, order: fv_assignment}
  - {type: prefix, value: '[CL]ə̀-', order: argument_marking}
