kind: Rules
rules:
  coalesce_before_i:
    input_pattern: '{<V_Mid><V_Low>}{[TBU]<T>}?<Boundary>?i'
    output_pattern: ɛ
    test_mappings:
    - - ka-i
      - kɛ
    - - pᴐ́-ì
      - pɛ̀
    - - kɜ̀-í
      - kɛ́
    - - pu-ì
      - pu-ì
  delete_vowel_before_vowel:
    input_pattern: <V>{[TBU]<T>}?<Boundary>?
    output_pattern: <Empty>
    right_context: <V>
    test_mappings:
    - - áɛ̀
      - ɛ̀
    - - î=ǔ
      - ǔ
    - - ᴐ̀í
      - í
  resolve_hiatus:
    rule_sequence:
    - coalesce_before_i
    - delete_vowel_before_vowel
    test_mappings:
    - - áɛ̀
      - ɛ̀
    - - î=ǔ
      - ǔ
    - - ᴐ̀í
      - ɛ́
    - - ka-i
      - kɛ
    - - pᴐ́-ì
      - pɛ̀
    - - kɜ̀-í
      - kɛ́
    - - pu-ì
      - pì
