# Phonological rules for modifying words already marked with tones
# Assumes [TBU] flags have already been cleaned
kind: Rules
rules:
  clear_all_tones:
    description: >
      Remove all tone markings from the input
    input_pattern: "<T>"
    output_pattern: ""
  clear_first_tone:
    description: >
      Remove the tone marking from the first TBU in a word
    input_pattern: "<T>"
    output_pattern: ""
    left_context: "[BOS]<Phone>+"
  replace_all_tones_with_low:
    description: >
      Replace any existing tone with a low tone on all TBUs
    rule_sequence: [$clear_all_tones, $all_low_tone]
  