data:
- kind: nested
  data:
  - kind: nested
    data:
    - description: Voiced stops
      kind: phones
      data:
        - b
        - d
        - g
      id: <B>
    - description: Voiceless stops
      kind: phones
      data:
        - p
        - t
        - c
        - q
      id: <P>
    description: Stops
    id: <Stp>
  - description: Fricatives
    kind: phones
    data:
      - f
      - v
      - s
      - z
      - x
      - h
      - j
    id: <Frc>
  - description: Sonorants
    kind: phones
    data:
      - r
      - l
      - y
      - "u\u0308"
    id: <Son>
  - description: Nasals
    kind: phones
    data:
      - m
      - n
      - "\xF1"
    id: <N>
  description: Consonants
  id: <C>
- kind: nested
  data:
  - description: High vowels
    kind: phones
    data:
      - i
      - u
    id: <V_High>
  - description: Mid vowels
    kind: phones
    data:
      - e
      - o
    id: <V_Mid>
  - description: Low vowels
    kind: phones
    data:
      - a
    id: <V_Low>
  description: Vowels
  id: <V>
- description: Stress marker
  kind: phones
  data:
    - "\u0301"
  id: <Stress>
- description: Phonology tags
  id: <PhonologyTags>
  kind: tags
  data:
    - '[BlockVowelAlternation]'
kind: Inventory
id: segments
