# Tira class prefixes
kind: FeatureMarkers
global_order: class_prefix
feature: class_marker
markers:
  # class prefixes in Tira include: l, g, r, ð, n, ŋ, ɲ, j, s, t̪
  # assume that the slot for the class prefix, marked with "[CL]",
  # is assigned at a previous stage (e.g. argument_marking)
  l:
    type: replace
    value: ["[CL]", l]
  g:
    type: replace
    value: ["[CL]", g]
  r:
    type: replace
    value: ["[CL]", r]
  ð:
    type: replace
    value: ["[CL]", ð]
  n:
    type: replace
    value: ["[CL]", n]
  ŋ:
    type: replace
    value: ["[CL]", ŋ]
  ɲ:
    type: replace
    value: ["[CL]", ɲ]
  j:
    type: replace
    value: ["[CL]", j]
  s:
    type: replace
    value: ["[CL]", s]
  t̪:
    type: replace
    value: ["[CL]", t̪]