# Imperfective auxiliary subject markers
kind: FeatureMarkers
global_order: argument_marker
feature: subject
markers:
  # singular subjects are associated with g-class
  # and plural with l-class
  # class contingencies are handled in ipfv_subj_obj_features.yaml (TODO)
  1sg:
    type: prefix
    value: íŋ-[CL]-
  2sg:
    type: prefix
    value: á-[CL]-
  1dual.incl:
    type: prefix
    value: á-[CL]-
  1pl.incl:
    type: prefix
    value: á-[CL]-
  1pl.excl:
    type: prefix
    value: ɲà-[CL]-
  2pl:
    type: prefix
    value: ɲá-[CL]-