kind: Inventory
data:
  consonants:
    ref: <C>
    stops:
      ref: <Stop>
      voiceless:
        ref: <P>
        phones:
        - p
        - t
        - k
      voiced:
        ref: <B>
        phones:
        - b
        - d
        - g
    fricatives:
      ref: <Fric>
      phones:
      - f
      - s
      - x
    affricates:
      ref: <Affr>
      phones:
      - ch
      - ts
      - dz
      - j
    nasals:
      ref: <N>
      phones:
      - m
      - n
      - ŋ
    liquids:
      ref: <Liq>
      phones:
      - l
      - r
    glides:
      ref: <Glide>
      phones:
      - y
      - w
  vowels:
    ref: <V>
    +ATR vowels:
      ref: <V_ATR>
      phones:
      - ə
      - e
      - i
      - o
      - u
    -ATR vowels:
      ref: <V_RTR>
      phones:
      - a
      - ɛ
      - ɪ
      - ɔ
      - ʊ
