kind: Inventory
data:
- ref: <C>
  name: Consonant
  _children:
  - ref: <Stp>
    name: Stops
    phones:
    - p
    - t
    - c
    - b
    - d
    - g
  - ref: <Frc>
    name: Fricative
    phones:
    - f
    - s
    - z
    - x
    - v
  - ref: <Son>
    name: Sonorant
    phones:
    - r
    - l
    - y
    - m
    - n
    - ñ
- ref: <V>
  name: Vowel
  phones:
  - a
  - e
  - i
  - o
  - u
- ref: <Stress>
  name: Stress
  phones:
  - DIAC:á
