kind: Inventory
data:
- _ref: <C>
  name: Consonant
  _children:
  - _ref: <Stp>
    name: Stops
    _phones:
    - p
    - t
    - c
    - b
    - d
    - g
  - _ref: <Frc>
    name: Fricative
    _phones:
    - f
    - s
    - z
    - x
    - v
  - _ref: <Son>
    name: Sonorant
    _phones:
    - r
    - l
    - y
    - m
    - n
    - ñ
- _ref: <V>
  name: Vowel
  _phones:
  - a
  - e
  - i
  - o
  - u
- _ref: <Stress>
  name: Stress
  _phones:
  - DIAC:á
