kind: MorphemeSet
features:
- singular_class
- plural_class
data:
- features:
    singular_class: g
    plural_class: unmarked
  morpheme: ""
- features:
    singular_class: unmarked
    plural_class: j
  morpheme: j-
- features:
    singular_class: unmarked
    plural_class: n
  morpheme: n-
- features:
    singular_class: ð
    plural_class: unmarked
  morpheme: ð-
- features:
    singular_class: unmarked
    plural_class: r
  morpheme: r-
