kind: Inventory
data:
  tone_flags:
    repr: "<TONE_SLOT>"
    flags: ["<TBU>", "<FLOAT>"]
  tones:
    repr: "<T>"
    F:
      repr: "<HL>"
      phones: ["\u0302"]
    H:
      repr: "<H>"
      phones: ["\u0301"]
    L:
      repr: "<L>"
      phones: ["\u0300"]
    R:
      repr: "<LH>"
      phones: ["\u030C"]
