# Phonological rules for associating [TBU] flags and tones to segments
kind: Rules
rules:
  # [TBU] flag insertion and cleanup
  add_tbus:
    description: >
      Add a tone-bearing unit (TBU) for each vowel and sonorant consonant
    input_pattern: ""
    output_pattern: "[TBU]"
    left_context: "(<V>|<R>|<N>)"
  remove_tbus_from_onset_c:
    description: >
      Remove TBUs from sonorant consonants in syllable onsets
    input_pattern: "[TBU]"
    output_pattern: ""
    left_context: "(<R>|<N>)"
    right_context: "<V>"
  remove_tbus_from_coda_c:
    description: >
      Remove TBUs from sonorant consonants in syllable codas
    input_pattern: "[TBU]"
    output_pattern: ""
    left_context: "<V>[TBU]<C>"
    right_context: "[EOS]"
  
  all_low_tone:
    description: >
      Assign a low tone to all TBUs
    input_pattern: "[TBU]"
    output_pattern: "[TBU]<L>"
  fill_low_tone:
    description: >
      Assign a low tone to any TBU that does not already have a tone (expects a string with some tones already assigned).
    input_pattern: "[TBU]"
    output_pattern: "[TBU]<L>"
    right_context: "{^<T>}"
  first_syllable_high_tone:
    description: >
      Assign a high tone to the first TBU in a word (expects a string with all tones removed).
    input_pattern: "[TBU]"
    output_pattern: "[TBU]<H>"
    left_context: "[BOS]<Phone>+"
  replace_first_tone_with_high:
    description: >
      Replace the tone on the first TBU in a word with a high tone
      (expects a string with tones already assigned).
    rule_sequence: [clear_first_tone, first_syllable_high_tone]
    test_mappings:
    - ["kùkù", "kúkù"]
    - ["kuku", "kúku"]
    - ["kúkù", "kúkù"]
    - ["kùkú", "kúkú"]
  hl_star_tone:
    description: >
      Assign a high tone to the first TBU and a low tone to all subsequent TBUs in a word
      (expects a string with all tones removed).
    rule_sequence: [clear_all_tones, first_syllable_high_tone, all_low_tone]