kind: MorphemeSequence
data:
- kind: MorphemeSet
  value: $noun_prefix_sg
- kind: MorphemeSet
  value: $noun_prefix_pl
- kind: Paradigm
  value: $noun_stem
- kind: Rule
  value: $mark_sg
- kind: Rule
  value: $mark_pl
