kind: MorphemeSequence
data:
- kind: MorphemeSet
  value: $class_prefixes
- kind: MorphemeSet
  value: $pre_stem_vowel
- kind: Paradigm
  value: $verb_stem
- kind: MorphemeSet
  value: $fv_class
- kind: Rule
  value: $resolve_hiatus
