kind: FeatureMarkers
feature: person_number
global_order: outer_suffix
global_markers:
- kind: rule
  value: harmonize_suffix
  order: post_affixation
markers:
  1sg:
  - kind: suffix
    value: -a
  2sg:
  - kind: suffix
    value: -ʊ
  3sg:
  - kind: suffix
    value: -i
  1pl:
  - kind: suffix
    value: -ko
  - kind: prefix
    value: ba-
  2pl: null
  3pl:
  - kind: rule
    value: $final_devoice
