# This is an Inventory config file
# This is where you specify phonemes as well as special tags
# for your language
kind: Inventory
id: segments
data:
  # type inv-phones, inv-tags or inv-nested to add more nodes!
  - description: Consonants
    id: <C>
    kind: nested
    data:
      - description: stops
        id: <Stop>
        kind: nested
        data:
          - description: voiced stops
            id: <VoicedStop>
            kind: nested
            data:
              - description: Voiced stops
                id: <VoicedStop>
                kind: phones
                data: [b, d, ɟ, g]
          - description: voiceless stops
            id: <VoicelessStop>
            kind: phones
            data: [p, t, c, k]
      - description: fricatives
        id: <Frc>
        kind: nested
        data:
          - description: voiced fricatives
            id: <VoicedFrc>
            kind: phones
            data: [v, ð]
          - description: voiceless fricative
            id: <VoicelessFrc>
            kind: phones
            data: [s]
      - description: sonorants
        id: <Son>
        kind: nested
        data:
          - description: nasals
            id: <N>
            kind: phones
            data: [m, n, ɲ, ŋ]
          - description: liquids
            id: <Liq>
            kind: phones
            data: [r, ɾ, ɽ, l]
          - description: glides
            id: <Glide>
            kind: phones
            data: [j, w]
  - description: vowels
    id: <V>
    kind: nested
    data:
      - description: high vowels
        id: <Vhi>
        kind: phones
        data: [i, u]
      - description: mid vowels
        id: <Vmid>
        kind: phones
        data: [e, o, ɛ, ɜ, ɔ]
      - description: low vowels
        id: <Vlo>
        kind: phones
        data: [a]
      - description: tone
        id: <T>
        # \u0301: combining acute (high tone)
        # \u0300: combining acute (high tone)
        # \u0302: combining grave (falling tone)
        # \u030C: combining caron (rising tone)
        kind: phones
        data: ["\u0301", "\u0300", "\u0302", "\u030C"]

## HELP FOR INVENTORY ##
# The inventory is built as a nested tree
# Each node of the tree contains either phones, tags, or other nodes
# that themeselves may contain phones, tags, or other nodes, etc.
# Each node must have three attributes:
#   description: A natural description of the node
#   id: A shorthand to refer to the node in parC
#     must be wrapped in <angle_brackets> and contain no spaces
#   nested OR phones OR tags
#     nested: nested nodes
#     phones: list of phones, each phone may be a single letter or multiple,
#       separated by commas e.g. [p, t, tʃ, k]
#       optionally wrapped in quotes e.g. ["p", "t", "tʃ", "k"]
#     tags: list of tags, each tag must be wrapped in both quotes and "[square_brackets]"
#       and not contain any spaces, e.g. [ "[TBU]", "[MORA]", "[SYLLABLE]"]
#       keep in mind the outermost square brackets indicate a list

# Below `consonants` and `vowels` are nested nodes,
# whereas `stops`, `nasals`, `high vowels` etc. are phone nodes
# and `tone tags` is a tag node

# - description: consonants
#   id: <C>
#   nested:
#   - description: Stops
#     id: <Stp>
#     phones: [p, t, k, b, d, g]
#   - description: Nasals
#     id: <N>
#     phones: [m, n, ŋ]
# - description: vowels
#   id: <V>
#   nested:
#   - description: high vowels
#     id: <V_High>
#     phones: [i, u]
#   - description: mid vowels
#     id: <V_Mid>
#     phones: [e, o]
#   - description: low_vowels
#     id: <V_Low>
#     phones: [a, æ]
# - description: tone slots
#   id: <ToneSlot>
#   tags: ["[TBU]", "[FLOAT]"]
