kind: FeatureMarkers
feature: number
markers:
  singular:
    kind: suffix
    value: '[sg]'
    order: number_flag
  plural:
  - kind: principal_part
    value: plural_stem
  - kind: suffix
    value: '[pl]'
    order: number_flag
