kind: Paradigm
part_of_speech: verb
order: [root_tone, final_vowel, argument_marker, class_prefix, resolve_hiatus, vowel_harmony, tone_processes]
global_markers:
  - type: rule
    value: "$hl_star_tone"
    order: root_tone
  - type: rule
    value: "$final_vowel_A"
    order: final_vowel
  - type: rule
    value: "$resolve_hiatus"
    order: resolve_hiatus
  - type: rule
    value: "$vowel_harmony"
    order: vowel_harmony
  - type: rule
    value: "$float_tones"
    order: tone_processes
feature_markers:
  class_marker: "$class_prefixes"
  deixis: itive
  object: "$ipfv_object_markers"
  tam: imperfective
feature_combinations: $ipfv_feature_set
contingent_markers:
- "$ipfv_subject_markers"
- "$ipfv_3object_markers"
