# Imperfective auxiliary object suffixes
kind: FeatureMarkers
global_order: argument_marker
feature: object
markers:
  1sg:
    type: suffix
    value: -ŋɛ̂
  2sg:
    type: suffix
    value: -ŋâ
  1dual.incl:
    type: suffix
    value: -tɛ́
  1pl.incl:
    type: suffix
    value: -tɛ́
  1pl.excl:
    type: suffix
    value: -éɲár
  2pl:
    type: suffix
    value: -tɛ́
  3pl:
    type: suffix
    value: '(-ĺ)|(-ló)'