# Imperfective auxiliary subject markers with a 3rd person object
kind: ContingentFeatureMarkers
global_order: argument_marker
features:
- subject
- object
markers:
  object:
    3sg:
      subject:
        1sg:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -ɛ́
        2sg:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -á
        3sg:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -ŋ
        1dual.incl:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -á-l
        1pl.incl:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -á-l
        1pl.excl:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -éɲâ
        2pl:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -éɲá
        3pl:
        - type: prefix
          value: "[CL]-"
        - type: suffix
          value: -l