# Present indicative suffixes for -er verbs
# comer: como, comes, come, comemos, coméis, comen
kind: FeatureMarkers
feature: person_number
global_order: suffixation
markers:
  1sg:
    type: suffix
    value: "-o"
  2sg:
    type: suffix
    value: "-es"
  3sg:
    type: suffix
    value: "-e"
  1pl:
    type: suffix
    value: "-emos"
  2pl:
    type: suffix
    value: "-éis"
  3pl:
    type: suffix
    value: "-en"
